[package]

name = "rust-bitrust"
version = "0.0.1"
authors = ["Pascal Hertleif <killercup@gmail.com>"]

[dependencies]
rustc-serialize = "0.2.5"

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs"
